import {ThemeMode} from '../types';
import {ColorVariablesType} from './types';

export const baseColors = {
  white: '#FFFFFF',
  black: '#000000',
  transparant: 'rgba(0,0,0,0)',

  gray25: '#FCFCFD',
  gray50: '#F9FAFB',
  gray100: '#F2F4F7',
  gray200: '#E4E7EC',
  gray300: '#D0D5DD',
  gray400: '#98A2B3',
  gray500: '#667085',
  gray600: '#475467',
  gray700: '#344054',
  gray800: '#182230',
  gray900: '#101828',
  gray950: '#0C111D',

  brand25: '#FCFAFF',
  brand50: '#F9F5FF',
  brand100: '#F4EBFF',
  brand200: '#E9D7FE',
  brand300: '#D6BBFB',
  brand400: '#B692F6',
  brand500: '#9E77ED',
  brand600: '#7F56D9',
  brand700: '#6941C6',
  brand800: '#53389E',
  brand900: '#42307D',
  brand950: '#2C1C5F',

  error25: '#FFFBFA',
  error50: '#FEF3F2',
  error100: '#FEE4E2',
  error200: '#FECDCA',
  error300: '#FDA29B',
  error400: '#F97066',
  error500: '#F04438',
  error600: '#D92D20',
  error700: '#B42318',
  error800: '#912018',
  error900: '#7A271A',
  error950: '#55160C',

  warning25: '#FFFCF5',
  warning50: '#FFFAEB',
  warning100: '#FEF0C7',
  warning200: '#FEDF89',
  warning300: '#FEC84B',
  warning400: '#FDB022',
  warning500: '#F79009',
  warning600: '#DC6803',
  warning700: '#B54708',
  warning800: '#93370D',
  warning900: '#7A2E0E',
  warning950: '#4E1D09',

  success25: '#F6FEF9',
  success50: '#ECFDF3',
  success100: '#DCFAE6',
  success200: '#ABEFC6',
  success300: '#75E0A7',
  success400: '#47CD89',
  success500: '#17B26A',
  success600: '#079455',
  success700: '#067647',
  success800: '#085D3A',
  success900: '#074D31',
  success950: '#053321',
};

const colorsLightMode: ColorVariablesType = {
  text: {
    primary: baseColors.gray900,
    primary_brand: baseColors.white,
    secondary: baseColors.gray700,
    secondary_hover: baseColors.gray800,
    secondary_brand: baseColors.brand200,
    tertiary: baseColors.gray600,
    tertiary_hover: baseColors.gray700,
    tertiary_brand: baseColors.brand200,
    quaternary: baseColors.gray500,
    quaternary_brand: baseColors.brand200,
    white: baseColors.white,
    disabled: baseColors.gray500,
    placeholder: baseColors.gray500,
    placeholder_subtle: baseColors.gray300,
    brand_primary: baseColors.brand900,
    brand_secondary: baseColors.brand700,
    brand_tertiary: baseColors.brand600,
    brand_tertiary_alt: baseColors.brand600,
    error_primary: baseColors.error600,
    warning_primary: baseColors.warning600,
    sucess_primary: baseColors.success600,
    success_badge: baseColors.success700,
  },
  border: {
    primary: baseColors.gray300,
    secondary: baseColors.gray200,
    tertiary: baseColors.gray100,
    disabled: baseColors.gray300,
    disabled_subtle: baseColors.gray200,
    brand: baseColors.brand500,
    brand_alt: baseColors.brand600,
    error: baseColors.error500,
    error_subtle: baseColors.error300,
    success: baseColors.success200,
  },
  forground: {
    primary: baseColors.gray900,
    secondary: baseColors.gray700,
    secondary_horver: baseColors.gray800,
    tertiary: baseColors.gray600,
    tertiary_hover: baseColors.gray700,
    quatenary: baseColors.gray500,
    quatenary_hover: baseColors.gray600,
    quinary: baseColors.gray400,
    quinary_hover: baseColors.gray500,
    senary: baseColors.gray300,
    white: baseColors.white,
    disabled: baseColors.gray400,
    disabled_subtle: baseColors.gray300,
    brand_primary: baseColors.brand600,
    brand_primary_alt: baseColors.brand600,
    brand_secondary: baseColors.brand500,
    error_primary: baseColors.error600,
    error_secondary: baseColors.error500,
    error_warning_primary: baseColors.warning600,
    error_warning_secondary: baseColors.warning500,
    success_primary: baseColors.success600,
    success_secondary: baseColors.success500,
  },
  background: {
    primary: baseColors.white,
    primary_alt: baseColors.white,
    primary_hover: baseColors.gray50,
    primary_solid: baseColors.gray950,
    secondary: baseColors.gray50,
    secondary_alt: baseColors.gray50,
    secondary_hover: baseColors.gray100,
    secondary_subtle: baseColors.gray25,
    secondary_solid: baseColors.gray600,
    tertiary: baseColors.gray100,
    quaternary: baseColors.gray200,
    active: baseColors.gray50,
    disabled: baseColors.gray100,
    disabled_subtle: baseColors.gray50,
    overlay: baseColors.gray950,
    brand_primary: baseColors.brand50,
    brand_primary_alt: baseColors.brand50,
    brand_secondary: baseColors.brand100,
    brand_solid: baseColors.brand600,
    brand_solid_hover: baseColors.brand700,
    brand_section: baseColors.brand800,
    brand_section_subtle: baseColors.brand700,
    error_primary: baseColors.error50,
    error_secondary: baseColors.error100,
    error_solid: baseColors.error600,
    warning_primary: baseColors.warning50,
    warning_secondary: baseColors.warning100,
    warning_solid: baseColors.warning600,
    success_primary: baseColors.success50,
    success_secondary: baseColors.success100,
    success_solid: baseColors.success600,
    success_badge: baseColors.success50,
  },
};

const colorsDarkMode: ColorVariablesType = {
  text: {
    primary: baseColors.gray50,
    primary_brand: baseColors.gray50,
    secondary: baseColors.gray300,
    secondary_hover: baseColors.gray200,
    secondary_brand: baseColors.brand300,
    tertiary: baseColors.gray400,
    tertiary_hover: baseColors.gray300,
    tertiary_brand: baseColors.brand200,
    quaternary: baseColors.gray500,
    quaternary_brand: baseColors.gray400,
    white: baseColors.white,
    disabled: baseColors.gray500,
    placeholder: baseColors.gray400,
    placeholder_subtle: baseColors.gray700,
    brand_primary: baseColors.gray50,
    brand_secondary: baseColors.gray300,
    brand_tertiary: baseColors.gray400,
    brand_tertiary_alt: baseColors.gray50,
    error_primary: baseColors.error400,
    warning_primary: baseColors.warning400,
    sucess_primary: baseColors.success400,
    success_badge: baseColors.success300,
  },
  border: {
    primary: baseColors.gray700,
    secondary: baseColors.gray800,
    tertiary: baseColors.gray800,
    disabled: baseColors.gray700,
    disabled_subtle: baseColors.gray800,
    brand: baseColors.brand400,
    brand_alt: baseColors.gray700,
    error: baseColors.error400,
    error_subtle: baseColors.error400,
    success: baseColors.success800,
  },
  forground: {
    primary: baseColors.white,
    secondary: baseColors.gray300,
    secondary_horver: baseColors.gray200,
    tertiary: baseColors.gray400,
    tertiary_hover: baseColors.gray300,
    quatenary: baseColors.gray400,
    quatenary_hover: baseColors.gray300,
    quinary: baseColors.gray500,
    quinary_hover: baseColors.gray400,
    senary: baseColors.gray600,
    white: baseColors.white,
    disabled: baseColors.gray500,
    disabled_subtle: baseColors.gray600,
    brand_primary: baseColors.brand500,
    brand_primary_alt: baseColors.gray300,
    brand_secondary: baseColors.brand500,
    error_primary: baseColors.error500,
    error_secondary: baseColors.error400,
    error_warning_primary: baseColors.warning500,
    error_warning_secondary: baseColors.warning400,
    success_primary: baseColors.success500,
    success_secondary: baseColors.success400,
  },
  background: {
    primary: baseColors.gray950,
    primary_alt: baseColors.gray900,
    primary_hover: baseColors.gray800,
    primary_solid: baseColors.gray900,
    secondary: baseColors.gray900,
    secondary_alt: baseColors.gray950,
    secondary_hover: baseColors.gray800,
    secondary_subtle: baseColors.gray900,
    secondary_solid: baseColors.gray600,
    tertiary: baseColors.gray800,
    quaternary: baseColors.gray700,
    active: baseColors.gray800,
    disabled: baseColors.gray800,
    disabled_subtle: baseColors.gray900,
    overlay: baseColors.gray800,
    brand_primary: baseColors.brand500,
    brand_primary_alt: baseColors.gray800,
    brand_secondary: baseColors.brand600,
    brand_solid: baseColors.brand600,
    brand_solid_hover: baseColors.brand500,
    brand_section: baseColors.gray800,
    brand_section_subtle: baseColors.gray950,
    error_primary: baseColors.error500,
    error_secondary: baseColors.error600,
    error_solid: baseColors.error600,
    warning_primary: baseColors.warning500,
    warning_secondary: baseColors.warning600,
    warning_solid: baseColors.warning600,
    success_primary: baseColors.success500,
    success_secondary: baseColors.success600,
    success_solid: baseColors.success600,
    success_badge: baseColors.success950,
  },
};

const getThemeColors = (mode: ThemeMode) => {
  return {
    ...(mode === 'light' ? colorsLightMode : colorsDarkMode),
  };
};

export const getDefaultTheme = (mode: ThemeMode) => {
  return {
    borderRadius: '8px',
    colors: getThemeColors(mode),
  };
};

export type Theme = ReturnType<typeof getDefaultTheme>;
